/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MultichartRouteImport } from './routes/multichart'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoinsIndexRouteImport } from './routes/coins/index'
import { Route as CoinsCoinIdRouteImport } from './routes/coins/$coinId'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MultichartRoute = MultichartRouteImport.update({
  id: '/multichart',
  path: '/multichart',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsIndexRoute = CoinsIndexRouteImport.update({
  id: '/coins/',
  path: '/coins/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsCoinIdRoute = CoinsCoinIdRouteImport.update({
  id: '/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heatmap': typeof HeatmapRoute
  '/multichart': typeof MultichartRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/coins/': typeof CoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heatmap': typeof HeatmapRoute
  '/multichart': typeof MultichartRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/coins': typeof CoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heatmap': typeof HeatmapRoute
  '/multichart': typeof MultichartRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/coins/': typeof CoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/heatmap'
    | '/multichart'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/coins/$coinId'
    | '/coins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/heatmap'
    | '/multichart'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/coins/$coinId'
    | '/coins'
  id:
    | '__root__'
    | '/'
    | '/heatmap'
    | '/multichart'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/coins/$coinId'
    | '/coins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeatmapRoute: typeof HeatmapRoute
  MultichartRoute: typeof MultichartRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  WatchlistRoute: typeof WatchlistRoute
  CoinsCoinIdRoute: typeof CoinsCoinIdRoute
  CoinsIndexRoute: typeof CoinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multichart': {
      id: '/multichart'
      path: '/multichart'
      fullPath: '/multichart'
      preLoaderRoute: typeof MultichartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins/': {
      id: '/coins/'
      path: '/coins'
      fullPath: '/coins/'
      preLoaderRoute: typeof CoinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins/$coinId': {
      id: '/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof CoinsCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeatmapRoute: HeatmapRoute,
  MultichartRoute: MultichartRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  WatchlistRoute: WatchlistRoute,
  CoinsCoinIdRoute: CoinsCoinIdRoute,
  CoinsIndexRoute: CoinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
